### ISSUE TITLE
Limit the stored history

### ISSUE THREAD

**Issue by bejanvaleriu** [jsdelivr/globalping-cli#145]
Hi,

About a week ago, I installed Globalping on my Ubuntu VM, which also runs Zabbix Server. I've created several items that execute the following commands every 10 minutes:

system.run["globalping ping {$TARGET} -J -L 1 -F '396982+Berlin'"]

This setup runs for ICMP and MTR across five fixed locations (ASN + city), resulting in a total of 15 calls every 10 minutes. However, I’ve noticed that Globalping is storing its measurements in the /tmp directory without automatically clearing them. Over the past 10 days, this has resulted in the creation of approximately 1.3 million directories, all named in the format globalping_688491_1729766790000, each containing a measurements file.

Is there a configuration or setting that can be adjusted to automatically clear these directories after a certain period of time? Or maybe to not store them?

Thank you for your assistance.

Best regards,
Valeriu

**Comment by radulucut** [comment]
Those files are session history files and are created based on the process id and creation time. I assume, in your case, a new process runs the command each time, which will result in a new session history file.

@jimaek @MartinKolarik maybe we can add a flag i.e `--disable-session` at the cmd level or a global one that persists in the config?

**Comment by bejanvaleriu** [comment]
For the time being, I’ve set up a cron job that runs every 2 hours to delete those directories. Is there a local patch or configuration change I can implement to prevent the creation of the session history files altogether?

**Comment by jimaek** [comment]
Not at the moment, but I'm sure we will address it in the next release shortly.

It would probably be best to solve the issue of accumulating files for everyone. Something like a max 100 and delete everything else.  I don't think anyone needs more than 10 previous values to be honest. Or maybe even use an embedded DB? What does everyone think?

**Comment by bejanvaleriu** [comment]
One idea would be to not store session history files by default. Instead, a new parameter, --save-session, could be introduced to enable the storage of session history files only when needed. Alternatively, a single logging file could be used to store the history of all sessions (if needed).

**Comment by MartinKolarik** [comment]
@radulucut let's add automated cleanup:
 - when writing to a file, keep at most 10k (most recent) records in it
 - keep no more than 100 directories in total (most recent)
 - deleting anything older (regardless of total count) than 7 days
 
 Additionally, we can add a global flag `--no-history` so that if someone doesn't want the history at all, they can disable it.

**Comment by jimaek** [comment]
Lets make --no-history auto-apply in CI mode too since we recommend it for scripting too

**Comment by jimaek** [comment]
If we add --no-history it should auto-apply to CI for sure. We can also not add anything and rely on auto-cleanup and in that case CI doesn't change. The second variant feels like a better solution to me

**Comment by MartinKolarik** [comment]
> If we add --no-history it should auto-apply to CI for sure.

CI mode, despite its name, isn't purely for CI jobs, and it is meant to only affect how we display the results. It applies, for example, in interactive sessions as soon as you pipe the output to a file or other program.

The auto clean-up should resolve the problem on its own. I would be fine with adding that extra flag so that if anyone really, really wants to avoid writing anything to the disk, they have a way of doing that. But if we add it, we don't activate it automatically.

**Comment by jimaek** [comment]
CI is for programmatic use, that includes both formatting and other potential options that make sense for scripting and actual CI. History is not needed there, so if the option exists it should be enabled.

But for now we can only do the auto cleanup
