### ISSUE TITLE
Update in-CLI docs and examples

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-cli#16]
I started the process here https://github.com/jsdelivr/globalping-cli/pull/14 but given that some command formats will change I don't want to merge it.

Please:
- Update all docs, examples and descriptions
- Ensure all data is accurate
- Consider what information could be useful to someone who has never seen the API (the CLI is standalone, we should not assume or require knowing how the system works to use the CLI)
- Add documentation about the magic location field and what it can accept
- Follow a unified format in descriptions, currently some describe how a command works, and others just assume you know what it is and just say that it executes it. 

Additionally:
- Lets group the commands, right now `help` is between dns and http as if its a measurement command. We should separate the measurement commands and CLI commands like help, completion and later credits and install-probe...

**Comment by ayuhito** [comment]
I think a big chunk of documentation that goes in-depth (e.g. explaining the magic field) should go on the website docs wherever the API docs will also be. That's where beginners should start since it's hard to condense everything down in-CLI and we need to probably make API doc references. The terminal is not the most readable thing in the world for longer description content after all.

**Comment by jimaek** [comment]
It's standard practice to have everything in the CLI itself and then just post everything the help output.

There are more complicated tools and they look fine with detailed explanations

**Comment by jimaek** [comment]
This task is also a good chance to test all commands and parameters to make sure they work correctly.
